services:
  n8n:
    container_name: ${DOCKER_NAME_PREFIX}-n8n
    image: n8nio/n8n:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT_TO_EXPOSE}:${N8N_PORT}"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: ${DOCKER_NAME_PREFIX}-postgres
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: ${DOCKER_NAME_PREFIX}-redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  n8n_data:
  postgres_data:
  redis_data: